//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaProje1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAcunmedyaAkademiEntities2 : DbContext
    {
        public DBAcunmedyaAkademiEntities2()
            : base("name=DBAcunmedyaAkademiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_About> TBL_About { get; set; }
        public virtual DbSet<TBL_Category> TBL_Category { get; set; }
        public virtual DbSet<TBL_Education> TBL_Education { get; set; }
        public virtual DbSet<TBL_Job> TBL_Job { get; set; }
        public virtual DbSet<TBL_Message> TBL_Message { get; set; }
        public virtual DbSet<TBL_Project> TBL_Project { get; set; }
        public virtual DbSet<TBL_Services> TBL_Services { get; set; }
        public virtual DbSet<TBL_Skill> TBL_Skill { get; set; }
        public virtual DbSet<TBL_Testimonial> TBL_Testimonial { get; set; }
        public virtual DbSet<TBL_Slider> TBL_Slider { get; set; }
        public virtual DbSet<TBL_Contact> TBL_Contact { get; set; }
    }
}
