//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaProje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Education
    {
        public int EducationID { get; set; }
        public Nullable<System.DateTime> StartedYear { get; set; }
        public Nullable<System.DateTime> EndYear { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Section { get; set; }
    }
}
